import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideBar from "@/components/SideBar";

export const metadata = {
    title: 'Welcome Back to Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return (
        <>
        <div className="grid h-screen min-h-screen w-full lg:grid-cols-[280px_1fr]">
            <SideBar />
            <div className="flex flex-col">
                <Header />
                <main>
                    {children}
                </main>
            </div>
        </div>

        <Footer />
        </>
    )
}
